[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17.14"
risc0-solana = { path = "../risc0-solana"}

[dev-dependencies]
ark-std = "0.4.0"
array-bytes = "6.2.2"
serde = "1.0.195"
serde_json = "1.0.111"

[lib]
crate-type = ["cdylib", "lib"]
