[package]
name = "proof-pre-processer"
version = "0.1.0"
edition = "2021"



[dependencies]
serde = "1.0.204"
serde_json = "1.0.118"
solana-program = "=1.17.14"
risc0-solana = { "path" = "/Users/hans/github.com/risc0/scratch/dev/hmrtn/sol/src/risc0-solana" }
