[package]
name = "proof-pre-processer"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
groth16-solana = "0.0.3"
num-bigint = "0.4.5"
num-traits = "0.2.19"
serde_json = "1.0.118"
solana-program = "=1.17.14"
